Repository leey00nsu/account-book-mission, pull requests merged in 2024-08, with the labels that each got.

#2 chore(#1) : fe,be express 초기 설정, prettier 초기 설정
  be/.gitignore
  be/.prettierrc.js
  be/app.js
  be/package-lock.json
  be/package.json
  fe/.gitignore
  fe/app.js
  fe/package-lock.json
  fe/package.json
Labels: chore

#10 chore(#4) : fe 웹팩 설정, express 설정
  fe/.gitignore
  fe/.prettierrc.js
  fe/app.js
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/pageA.html
  fe/public/pageB.html
  fe/src/features/test.js
  fe/src/index.js
  fe/webpack.config.js
Labels: chore

#14 feat(#11) : transaction-report-list 레이아웃
  fe/public/report.css
  fe/public/report.html
Labels: feature

#16 feat(#15) : transaction-report-list 데이터 반영
  fe/app.js
  fe/src/features/transactionReport.js
  fe/src/index.js
  fe/src/utils/addComma.js
Labels: feature

#17 feat(#12) : report header 레이아웃 구성
  fe/public/report.css
  fe/public/report.html
Labels: feature

#18 feat(#15) : transaction-report-header 날짜 쿼리스트링 반영
  fe/src/features/transactionReport.js
  fe/src/index.js
  fe/src/utils/getFirstAndLastDay.js
Labels: feature

#22 Feature/6 account book transaction list rayout
  be/.gitignore
  be/app.js
  be/db/database.js
  be/package-lock.json
  be/package.json
  fe/app.js
  fe/package-lock.json
  fe/package.json
  fe/public/account_book.html
  fe/public/test.html
  fe/src/features/account_book.js
  fe/src/features/test.js
  fe/src/index.js
  public/api.png
  public/erd.png
  public/flow.png
  public/wire-frame.png
Labels: feature

#23 feat(#8) : account-transaction-form 레이아웃 구성
  fe/public/accountBook.css
  fe/public/account_book.html
Labels: feature

#26 feat(#25) : DB 수정 했습니다.
  .ignore
  be/.gitignore
  be/db/database.js
  be/package.json
  fe/.gitignore
  fe/package.json
Labels: feature

#28 feat(#27) : 날짜별, 지출 수입 별 완료
  be/app.js
  be/db/database.js
  fe/public/account_book.html
  fe/public/transactionList.css
  fe/src/features/account_book.js
  fe/src/index.js
Labels: feature

#30 refactor(#29) : 프로젝트 구조 개선
  be/app.js
  be/db/database.js
  be/package.json
  fe/app.js
  fe/public/accountBook.css
  fe/public/accountBook.html
  fe/public/index.html
  fe/public/pageA.html
  fe/public/pageB.html
  fe/public/report.html
  fe/public/test.html
  fe/public/transactionList.css
  fe/src/features/accountBook.js
  fe/src/features/account_book.js
  fe/src/index.js
  fe/src/utils/addComma.js
  fe/src/utils/extractNumber.js
Labels: refactor

#31 feat(#15) : transaction report api 추가
  fe/public/accountBook.html
  fe/src/features/accountBook.js
  fe/src/features/transactionReport.js
  fe/src/index.js
Labels: feature

#32 fix(#15) : transaction report api be 적용 수정
  be/app.js
  be/db/database.js
Labels: fix

#34 refactor(#33) : outcome -> expense 단어 교체
  be/app.js
  be/db/database.js
  fe/public/accountBook.html
  fe/public/report.html
  fe/src/features/accountBook.js
  fe/src/features/transactionReport.js
Labels: refactor

#36 feat(#35) : 입력 api 구현
  be/app.js
  be/db/database.js
  fe/package-lock.json
  fe/package.json
  fe/public/accountBook.html
  fe/src/features/accountBook.js
Labels: feature

#37 refactor(#29) : 구조 리팩토링
  be/package-lock.json
  be/package.json
  fe/package.json
  fe/public/accountBook.css
  fe/public/accountBook.html
  fe/public/report.css
  fe/public/report.html
  fe/src/features/accountBook.js
  fe/src/features/transactionReport.js
Labels: refactor

#38 docs(#29) : README.md 반영
  .ignore
  README.md
  public/api.png
  public/erd.png
  public/flow.png
  public/wire-frame.png
Labels: refactor
